use bytemuck::{Pod, Zeroable};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Heartbeat {
    pub seed: i32,
    pub wants_country: u8,
}

#[derive(Serialize, Deserialize)]
pub struct Stats {
    pub connected: u32,
    pub seed: i32,
    #[serde(with = "serde_arrays")]
    pub country_heatmap: [f32; COUNTRIES.len()],
}

#[derive(Clone, Copy, Debug, Pod, Zeroable, Default)]
#[repr(C)]
pub struct StoredIpStats {
    pub first_seen: u64,
    pub last_seen: u64,
    pub hits: u32,
    pub cum_duration: u32,
    pub country: u8,
    pub _reserved: [u8; 7],
}

#[derive(Clone, Copy, Debug, Pod, Zeroable)]
#[repr(C)]
pub struct StoredCountryStats {
    pub seed: i64,
    pub active: u32,
    pub unique: u32,
    pub cum_duration: u32,
    pub _reserved: [u8; 12],
}

pub fn search_country(code: &str) -> Option<u8> {
    let code_bytes: [u8; 2] = code.as_bytes().try_into().ok()?;
    COUNTRIES
        .binary_search_by_key(&code_bytes, |&(code, _)| code)
        .ok()
        .map(|x| x as u8)
}

pub fn get_country_name(idx: u8) -> &'static str {
    // SAFETY: Guaranteed to be ASCII, so no issues with this
    unsafe { str::from_utf8_unchecked(&COUNTRIES[idx as usize].0) }
}

// pub fn iter_map_countries() -> impl Iterator<Item = u8> {
//     let code_bytes: [u8; 2] = code.as_bytes().try_into().ok()?;
//     COUNTRIES
//         .binary_search_by_key(&code_bytes, |&(code, _)| code)
//         .ok()
//         .map(|x| x as u8)
// }

// ISO 3166-1 alpha-2 country codes, including whether or not they're included in the world map
pub static COUNTRIES: [([u8; 2], bool); 252] = [
    // AA is explicitly reserved and will never be a real country
    (*b"AA", false),
    (*b"AD", false),
    (*b"AE", true),
    (*b"AF", true),
    (*b"AG", false),
    (*b"AI", false),
    (*b"AL", true),
    (*b"AM", true),
    (*b"AO", true),
    (*b"AQ", false),
    (*b"AR", true),
    (*b"AS", false),
    (*b"AT", true),
    (*b"AU", true),
    (*b"AW", false),
    (*b"AX", false),
    (*b"AZ", true),
    (*b"BA", true),
    (*b"BB", false),
    (*b"BD", true),
    (*b"BE", true),
    (*b"BF", true),
    (*b"BG", true),
    (*b"BH", false),
    (*b"BI", true),
    (*b"BJ", true),
    (*b"BL", false),
    (*b"BM", false),
    (*b"BN", true),
    (*b"BO", true),
    (*b"BQ", false),
    (*b"BR", true),
    (*b"BS", true),
    (*b"BT", true),
    (*b"BV", false),
    (*b"BW", true),
    (*b"BY", true),
    (*b"BZ", true),
    (*b"CA", true),
    (*b"CC", false),
    (*b"CD", true),
    (*b"CF", true),
    (*b"CG", true),
    (*b"CH", true),
    (*b"CI", true),
    (*b"CK", false),
    (*b"CL", true),
    (*b"CM", true),
    (*b"CN", true),
    (*b"CO", true),
    (*b"CR", true),
    (*b"CU", true),
    (*b"CV", true),
    (*b"CW", false),
    (*b"CX", false),
    (*b"CY", true),
    (*b"CZ", true),
    (*b"DE", true),
    (*b"DJ", true),
    (*b"DK", true),
    (*b"DM", true),
    (*b"DO", true),
    (*b"DZ", true),
    (*b"EC", true),
    (*b"EE", true),
    (*b"EG", true),
    (*b"EH", false),
    (*b"ER", true),
    (*b"ES", true),
    (*b"ET", true),
    (*b"FI", true),
    (*b"FJ", false),
    (*b"FK", true),
    (*b"FM", false),
    (*b"FO", false),
    (*b"FR", true),
    (*b"GA", true),
    (*b"GB", true),
    (*b"GD", false),
    (*b"GE", true),
    (*b"GF", false),
    (*b"GG", false),
    (*b"GH", true),
    (*b"GI", false),
    (*b"GL", true),
    (*b"GM", true),
    (*b"GN", true),
    (*b"GP", false),
    (*b"GQ", true),
    (*b"GR", true),
    (*b"GS", false),
    (*b"GT", true),
    (*b"GU", false),
    (*b"GW", true),
    (*b"GY", true),
    (*b"HK", false),
    (*b"HM", false),
    (*b"HN", true),
    (*b"HR", true),
    (*b"HT", true),
    (*b"HU", true),
    (*b"ID", true),
    (*b"IE", true),
    (*b"IL", true),
    (*b"IM", false),
    (*b"IN", true),
    (*b"IO", false),
    (*b"IQ", true),
    (*b"IR", true),
    (*b"IS", true),
    (*b"IT", true),
    (*b"JE", false),
    (*b"JM", true),
    (*b"JO", true),
    (*b"JP", true),
    (*b"KE", true),
    (*b"KG", true),
    (*b"KH", true),
    (*b"KI", false),
    (*b"KM", true),
    (*b"KN", false),
    (*b"KP", true),
    (*b"KR", true),
    (*b"KW", true),
    (*b"KY", false),
    (*b"KZ", true),
    (*b"LA", true),
    (*b"LB", true),
    (*b"LC", true),
    (*b"LI", false),
    (*b"LK", true),
    (*b"LR", true),
    (*b"LS", true),
    (*b"LT", true),
    (*b"LU", true),
    (*b"LV", true),
    (*b"LY", true),
    (*b"MA", true),
    (*b"MC", false),
    (*b"MD", true),
    (*b"ME", true),
    (*b"MF", false),
    (*b"MG", true),
    (*b"MH", false),
    (*b"MK", true),
    (*b"ML", true),
    (*b"MM", true),
    (*b"MN", true),
    (*b"MO", false),
    (*b"MP", false),
    (*b"MQ", false),
    (*b"MR", true),
    (*b"MS", false),
    (*b"MT", true),
    (*b"MU", true),
    (*b"MV", true),
    (*b"MW", true),
    (*b"MX", true),
    (*b"MY", true),
    (*b"MZ", true),
    (*b"NA", true),
    (*b"NC", true),
    (*b"NE", true),
    (*b"NF", false),
    (*b"NG", true),
    (*b"NI", true),
    (*b"NL", true),
    (*b"NO", true),
    (*b"NP", true),
    (*b"NR", false),
    (*b"NU", false),
    (*b"NZ", true),
    (*b"OM", true),
    (*b"PA", true),
    (*b"PE", true),
    (*b"PF", false),
    (*b"PG", true),
    (*b"PH", true),
    (*b"PK", true),
    (*b"PL", true),
    (*b"PM", false),
    (*b"PN", false),
    (*b"PR", true),
    (*b"PS", false),
    (*b"PT", true),
    (*b"PW", false),
    (*b"PY", true),
    (*b"QA", true),
    (*b"RE", false),
    (*b"RO", true),
    (*b"RS", true),
    (*b"RU", true),
    (*b"RW", true),
    (*b"SA", true),
    (*b"SB", true),
    (*b"SC", true),
    (*b"SD", true),
    (*b"SE", true),
    (*b"SG", true),
    (*b"SH", false),
    (*b"SI", true),
    (*b"SJ", false),
    (*b"SK", true),
    (*b"SL", true),
    (*b"SM", false),
    (*b"SN", true),
    (*b"SO", true),
    (*b"SR", true),
    (*b"SS", true),
    (*b"ST", true),
    (*b"SV", true),
    (*b"SX", false),
    (*b"SY", true),
    (*b"SZ", true),
    (*b"TC", false),
    (*b"TD", true),
    (*b"TF", false),
    (*b"TG", true),
    (*b"TH", true),
    (*b"TJ", true),
    (*b"TK", false),
    (*b"TL", false),
    (*b"TM", true),
    (*b"TN", true),
    (*b"TO", false),
    (*b"TR", true),
    (*b"TT", true),
    (*b"TV", false),
    (*b"TW", true),
    (*b"TZ", true),
    (*b"UA", true),
    (*b"UG", true),
    (*b"UM", false),
    (*b"US", true),
    (*b"UY", true),
    (*b"UZ", true),
    (*b"VA", false),
    (*b"VC", true),
    (*b"VE", true),
    (*b"VG", false),
    (*b"VI", false),
    (*b"VN", true),
    (*b"VU", true),
    (*b"WF", false),
    (*b"WS", false),
    (*b"XK", false),
    (*b"XW", false),
    (*b"YE", true),
    (*b"YT", false),
    (*b"ZA", true),
    (*b"ZM", true),
    (*b"ZW", true),
];

// Non-standard global code (XW)
pub const WORLDWIDE: u8 = 246;
